env:
  TERM: xterm-256color

font:
  normal:
    family: Hack Nerd Font Mono 
    style: Regular

  bold:
    family: Hack Nerd Font Mono 
    style: Bold

  italic:
    family: Hack Nerd Font Mono 
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono 
    style: Bold Italic

  size: 14

colors:
  primary:
    background: '#2d3441'
    foreground: '#cdcecf'

  normal:
    black:   '#3b4252'
    red:     '#bf616a'
    green:   '#a3be8c'
    yellow:  '#ebcb8b'
    blue:    '#81a1c1'
    magenta: '#b48ead'
    cyan:    '#88c0d0'
    white:   '#e5e9f0'

  bright:
    black:   '#4c566a'
    red:     '#d06f79'
    green:   '#b1d196'
    yellow:  '#f0d399'
    blue:    '#81a1c1'
    magenta: '#c895bf'
    cyan:    '#8fbcbb'
    white:   '#e7ecf4'

  dim:
    black:   '#373e4d'
    red:     '#94545d'
    green:   '#809575'
    yellow:  '#b29e75'
    blue:    '#68809a'
    magenta: '#8c738c'
    cyan:    '#6d96a5'
    white:   '#aeb3bb'

  indexed_colors:
    - { index: 16, color: '#c9826b' }
    - { index: 17, color: '#bf88bc' }
